#signup
# POST http://localhost:8087/auth/signup/
# Content-Type: application/x-www-form-urlencoded

# email=a2@a.com&password=password

# login 
# POST http://localhost:8087/auth/login/password/
# Content-Type: application/x-www-form-urlencoded

# username=a@a.com&password=password

#get token from password auth
# POST http://localhost:8087/token/

# username=a@a.com&password=password

# see common auth status
# GET http://localhost:8087/auth/
# Cookie: access_token=token

#get token from email magic link 
# POST http://localhost:8087/auth/login/email-magic-link/
# Content-Type: application/json
    
# {
#     "email": "a@a.com"
# }

#verify magic token
#POST http://localhost:8087/auth/verify-magic-link/
#Authorization: Bearer token

# get user sessions
GET http://localhost:8087/user/id/sessions/
Cookie: access_token=token

