POST http://localhost:8087/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YWFhYWE4YS0wMWQ5LTQ4OWEtOGFmZC01NTU5MDA2ZjNkYzQiLCJpYXQiOjE3MjQ3MDY1NzYuMTU3MjAyfQ.KgFa_s14U-Ci0bl5Lv-8PFA3uOnFBRJNOZCrz6Dy_qU

