AUTH_KEY: auth
HEADER_KEYS:
  auth_logout: x-auth-logout
FRONTEND_URLS:
  verify_signup: /welcome
  verify_magic_link: /verify-magic-link
  galleries: /galleries
SCOPE_NAME_MAPPING:
  admin: 1
  user.read: 2
  user.write: 3
VISIBILITY_LEVEL_NAME_MAPPING:
  public: 1
  private: 2
PERMISSION_LEVEL_NAME_MAPPING:
  editor: 2
  viewer: 1
USER_ROLE_NAME_MAPPING:
  admin: 2
  user: 1
USER_ROLE_SCOPES:
  admin:
    - admin
    - user.read
    - user.write
  user:
    - user.read
    - user.write
    # path is relative to the config file
OPENAPI_SCHEMA_PATH: ../../openapi_schema.json
OTP_LENGTH: 6
GOOGLE_CLIENT_SECRET_PATH: google_client_secret.json
