/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/": {
    /** Auth Root */
    get: operations["auth_root_auth__get"];
  };
  "/token/": {
    /** Post Token */
    post: operations["post_token_token__post"];
  };
  "/auth/login/password/": {
    /** Login */
    post: operations["login_auth_login_password__post"];
  };
  "/auth/signup/": {
    /** Sign Up */
    post: operations["sign_up_auth_signup__post"];
  };
  "/auth/login/email-magic-link/": {
    /** Login With Email Magic Link */
    post: operations["login_with_email_magic_link_auth_login_email_magic_link__post"];
  };
  "/auth/verify-magic-link/": {
    /** Verify Magic Link */
    post: operations["verify_magic_link_auth_verify_magic_link__post"];
  };
  "/auth/login/google/": {
    /** Login With Google */
    post: operations["login_with_google_auth_login_google__post"];
  };
  "/auth/logout/": {
    /** Logout */
    post: operations["logout_auth_logout__post"];
  };
  "/users/available/username/{username}/": {
    /** User Username Available */
    get: operations["user_username_available_users_available_username__username___get"];
  };
  "/users/available/email/{email}/": {
    /** User Email Available */
    get: operations["user_email_available_users_available_email__email___get"];
  };
  "/users/username/{username}": {
    /** Get User By Username */
    get: operations["get_user_by_username_users_username__username__get"];
  };
  "/users/{user_id}": {
    /** Get User By Id */
    get: operations["get_user_by_id_users__user_id__get"];
  };
  "/users/": {
    /** Post User */
    post: operations["post_user_users__post"];
  };
  "/profile/page/": {
    /** Get Pages Profile */
    get: operations["get_pages_profile_profile_page__get"];
  };
  "/home/page/": {
    /** Get Home Page */
    get: operations["get_home_page_home_page__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Body_login_auth_login_password__post */
    Body_login_auth_login_password__post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: string | null;
      /** Client Secret */
      client_secret?: string | null;
    };
    /** Body_post_token_token__post */
    Body_post_token_token__post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: string | null;
      /** Client Secret */
      client_secret?: string | null;
    };
    /** Body_sign_up_auth_signup__post */
    Body_sign_up_auth_signup__post: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** DetailOnlyResponse */
    DetailOnlyResponse: {
      /** Detail */
      detail: string;
    };
    /** GetAuthBaseReturn */
    GetAuthBaseReturn: {
      user?: components["schemas"]["UserPrivate"] | null;
      /** Scopes */
      scopes?: number[] | null;
      /** Expiry */
      expiry?: string | null;
    };
    /** GetAuthReturn */
    GetAuthReturn: {
      auth: components["schemas"]["GetAuthBaseReturn"];
    };
    /** GetHomePageResponse */
    GetHomePageResponse: {
      auth: components["schemas"]["GetAuthBaseReturn"];
    };
    /** GetProfilePageResponse */
    GetProfilePageResponse: {
      auth: components["schemas"]["GetAuthBaseReturn"];
      user?: components["schemas"]["UserPrivate"] | null;
    };
    /** GoogleAuthRequest */
    GoogleAuthRequest: {
      /** Access Token */
      access_token: string;
    };
    /** GoogleAuthResponse */
    GoogleAuthResponse: {
      auth: components["schemas"]["GetAuthBaseReturn"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ItemAvailableResponse */
    ItemAvailableResponse: {
      /** Available */
      available: boolean;
    };
    /** LoginResponse */
    LoginResponse: {
      auth: components["schemas"]["GetAuthBaseReturn"];
    };
    /** LoginWithEmailMagicLinkRequest */
    LoginWithEmailMagicLinkRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** NotFoundResponse */
    NotFoundResponse: {
      /** Detail */
      detail: string;
    };
    /** SignupResponse */
    SignupResponse: {
      auth: components["schemas"]["GetAuthBaseReturn"];
    };
    /** UserCreate */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password?: string | null;
    };
    /** UserPrivate */
    UserPrivate: {
      /** Id */
      id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Username */
      username: string | null;
    };
    /** UserPublic */
    UserPublic: {
      /** Id */
      id: string;
      /** Username */
      username: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VerifyMagicLinkRequest */
    VerifyMagicLinkRequest: {
      auth: components["schemas"]["GetAuthBaseReturn"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Auth Root */
  auth_root_auth__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GetAuthReturn"];
        };
      };
    };
  };
  /** Post Token */
  post_token_token__post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_post_token_token__post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login */
  login_auth_login_password__post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_password__post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Could not validate credentials */
      401: {
        content: {
          "application/json": components["schemas"]["DetailOnlyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Sign Up */
  sign_up_auth_signup__post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_sign_up_auth_signup__post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SignupResponse"];
        };
      };
      /** @description User already exists */
      409: {
        content: {
          "application/json": components["schemas"]["DetailOnlyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Login With Email Magic Link */
  login_with_email_magic_link_auth_login_email_magic_link__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginWithEmailMagicLinkRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DetailOnlyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Verify Magic Link */
  verify_magic_link_auth_verify_magic_link__post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VerifyMagicLinkRequest"];
        };
      };
      /** @description Invalid token */
      401: {
        content: {
          "application/json": components["schemas"]["DetailOnlyResponse"];
        };
      };
    };
  };
  /** Login With Google */
  login_with_google_auth_login_google__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GoogleAuthRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GoogleAuthResponse"];
        };
      };
      /** @description Invalid token */
      400: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Logout */
  logout_auth_logout__post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DetailOnlyResponse"];
        };
      };
    };
  };
  /** User Username Available */
  user_username_available_users_available_username__username___get: {
    parameters: {
      path: {
        username: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ItemAvailableResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** User Email Available */
  user_email_available_users_available_email__email___get: {
    parameters: {
      path: {
        email: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ItemAvailableResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get User By Username */
  get_user_by_username_users_username__username__get: {
    parameters: {
      path: {
        username: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserPublic"];
        };
      };
      /** @description User not found */
      404: {
        content: {
          "application/json": components["schemas"]["NotFoundResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get User By Id */
  get_user_by_id_users__user_id__get: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserPublic"];
        };
      };
      /** @description User not found */
      404: {
        content: {
          "application/json": components["schemas"]["NotFoundResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Post User */
  post_user_users__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserPrivate"];
        };
      };
      /** @description User already exists */
      409: {
        content: {
          "application/json": components["schemas"]["DetailOnlyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Pages Profile */
  get_pages_profile_profile_page__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GetProfilePageResponse"];
        };
      };
    };
  };
  /** Get Home Page */
  get_home_page_home_page__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GetHomePageResponse"];
        };
      };
    };
  };
}
