/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    /** Read Root */
    get: operations["read_root__get"];
  };
  "/studios/": {
    /** Get Studios */
    get: operations["get_studios_studios__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Studio */
    Studio: {
      /** Id */
      _id: string;
      /** Dir Name */
      dir_name: string;
      /** Name */
      name?: string | null;
    };
    /** Studios */
    Studios: {
      /** Studios */
      studios?: {
        [key: string]: components["schemas"]["Studio"];
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Read Root */
  read_root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Get Studios */
  get_studios_studios__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Studios"];
        };
      };
    };
  };
}
